version: '3.8'

services:
  db:
    image: postgres:15
    container_name: local_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=localpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "55432:5432"
    volumes:
      - ./devops:/docker-entrypoint-initdb.d:ro
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
    driver: local
